### ISSUE TITLE
Think about how we structure content pages

### ISSUE THREAD

**Issue by hepplerj** [chnm/bom#101]
Pages like how to use the data, student research, about the data (context), how to use the API, and so forth.

**Comment by hepplerj** [comment]
A few related issues: 

- [ ] #31 
- [ ] #28 
- [ ] #128 
- [ ] #133 
- [ ] #116 
- [ ] #111

**Comment by jmotis** [comment]
consolidating issues

**Comment by hepplerj** [comment]
Consolidated with #111
