### ISSUE TITLE
Interface design of the website

### ISSUE THREAD

**Issue by hepplerj** [chnm/bom#44]
This is an ongoing, iterative list of interface design choices and discussions for the Bills of Mortality project.

## Database

- [x] hover-overs to describe causes of death
- [x] filter under accordion interface

## Visualizations

- [ ] time slider of geo information

## Context / history

- [ ] causes of death 

## Exports 

- [ ] download by filter selection
- [ ] download shapefiles of London over time
- [ ] download networks of parishes over time

**Comment by jmotis** [comment]
OBE
